# Generated by Django 3.2 on 2022-10-13 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Realstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realstate_title', models.CharField(blank=True, max_length=50, null=True)),
                ('offer_type', models.CharField(blank=True, choices=[('for_rent', 'for rent'), ('for_sale', 'for sale')], max_length=20, null=True)),
                ('realstate_type', models.CharField(blank=True, choices=[('dept', 'department'), ('house', 'house'), ('land', 'land'), ('basement', 'basement')], max_length=50, null=True)),
                ('ownership_type', models.CharField(blank=True, choices=[('free', 'free'), ('waqf', 'waqf')], max_length=20, null=True)),
                ('realstate_description', models.TextField(blank=True, null=True)),
                ('realstate_town', models.CharField(blank=True, choices=[('sanaa', "sana'a"), ('Dhamar', 'Dhamar'), ('Taiz', 'Taiz')], max_length=50, null=True)),
                ('realstate_area', models.CharField(blank=True, max_length=50, null=True)),
                ('realstate_price', models.IntegerField(blank=True, null=True)),
                ('is_negotiable', models.BooleanField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Realstate',
                'verbose_name_plural': 'Realstates',
            },
        ),
        migrations.CreateModel(
            name='RealstateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realstate.realstate')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
